# GET https://bate-ponto-api.onrender.com/points
GET http://localhost:3333/points

###

GET http://localhost:3333/point/9dc2ae07-a9ed-4841-864b-e27c4eb21ca4

###

POST http://localhost:3333/point
Content-Type: application/json

{
  "date": "19/02/2024",
  "activities": [
    {
      "startTime": "10:00",
      "endTime": "11:00",
      "description": "Refatorando componente",
      "category": "Tarefa"
    },
    {
      "startTime": "11:00",
      "endTime": "13:00",
      "description": "Refatorando fluxo de login",
      "category": "Tarefa"
    },
    {
      "startTime": "13:00",
      "endTime": "14:00",
      "description": "Almoço",
      "category": "Intervalo"
    },
  ]
}

###

PUT  http://localhost:3333/points/9dc2ae07-a9ed-4841-864b-e27c4eb21ca4
Content-Type: application/json

{
  "date": "20/20/2024",
  "activities": [
    {
      "startTime": "10:00",
      "endTime": "11:00",
      "description": "Refatorando componente",
      "category": "Tarefa"
    },
    {
      "startTime": "11:00",
      "endTime": "13:00",
      "description": "Refatorando fluxo de login",
      "category": "Tarefa"
    },
    {
      "startTime": "13:00",
      "endTime": "14:00",
      "description": "Almoço",
      "category": "Intervalo"
    },
    {
      "startTime": "17:00",
      "endTime": "18:37",
      "description": "Lanche",
      "category": "Intervalo"
    }
  ]
}

###

DELETE  http://localhost:3333/point/2dee5487-0f2d-4efc-93b5-ec8e8426c07b